# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OCExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OCExample
  pod 'SJBaseVideoPlayer', :git => 'https://gitee.com/changsanjiang/SJBaseVideoPlayer.git'
  pod 'SJVideoPlayer', :git => 'https://gitee.com/changsanjiang/SJVideoPlayer.git'

  target 'OCExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCExampleUITests' do
    # Pods for testing
  end

end
