# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AriaM3U8Downloader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'Alamofire'
  pod 'RxAlamofire'
  pod 'GCDWebServer/WebDAV'

  # Pods for AriaM3U8Downloader

  target 'AriaM3U8DownloaderTests' do
    # Pods for testing
  end

end
